- hosts: target
  tasks:
    - name: copy artifact
      ansible.builtin.copy:
        src: main.rb
        dest: /home/vagrant/sample-ruby
        mode: "0777"
        
    - name: ruby installation
      command: sudo yum install -y ruby.x86_64
      tags: ruby
      
    - name: sinatra installation
      command: gem install sinatra -v1.4.8
        
    - name: create simple service template
      become: true
      template:
        src: sample-ruby.service.j2
        dest: /etc/systemd/system/sample-ruby.service
    - name: run sample ruby service
      become: true
      ansible.builtin.systemd:
        state: restarted
        name: sample-ruby
