- hosts: target
  tasks:
        
    - name: copy artifact
      ansible.builtin.copy:
        src: main.rb
        dest: /home/vagrant/sample-rb
        mode: "0777"

    - name: install ruby
      command: sudo yum install -y ruby

    - name: install sinatra
      command: gem install sinatra -v1.4.8

    - name: create simple service template
      become: true
      template:
        src: sample-rb.service.j2
        dest: /etc/systemd/system/sample-rb.service

    - name: run sample-rb service
      become: true
      ansible.builtin.systemd:
        state: restarted
        name: sample-rb
